Use rpm file to add centos repo (#240)
Old variant start cause error like this:

```
Step 9/12 : RUN rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8320CA65CB2DE8E5"
 ---> Running in 994ecc9c51d5
error: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8320CA65CB2DE8E5: key 1 not an armored public key.
The command '/bin/sh -c rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8320CA65CB2DE8E5"' returned a non-zero code: 1
```

Don't know the reason, but adding repo by rpm is more advance way